version: '3.2'

services:
  dapptools:
    restart: unless-stopped
    depends_on:
      - statediff-migrations
    image: vulcanize/dapptools:v0.29.0-v1.10.8-statediff-0.0.27
    environment:
      DB_USER: vdbm
      DB_NAME: vulcanize_public
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: password
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"

  statediff-migrations:
    restart: on-failure
    depends_on:
      - db
    image: vulcanize/statediff-migrations:0.7.0
    environment:
      DATABASE_USER: vdbm
      DATABASE_NAME: vulcanize_public
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: password

  db:
    restart: always
    image: postgres:10.12-alpine
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_public"
      POSTGRES_PASSWORD: "password"
    volumes:
     - vdb_db_eth_server:/var/lib/postgresql/data
    ports:
     - "127.0.0.1:8077:5432"

  eth-server:
    restart: unless-stopped
    depends_on:
      - db
    build:
      context: ./
      cache_from:
       - alpine:latest
       - golang:1.13-alpine
    environment:
      IPLD_SERVER_GRAPHQL: "true"
      IPLD_POSTGRAPHILEPATH: http://graphql:5000
      ETH_SERVER_HTTPPATH: 0.0.0.0:8081
      VDB_COMMAND: "serve"
      ETH_CHAIN_CONFIG: "/tmp/chain.json"
      DATABASE_NAME: "vulcanize_public"
      DATABASE_HOSTNAME: "db"
      DATABASE_PORT: 5432
      DATABASE_USER: "vdbm"
      DATABASE_PASSWORD: "password"
      ETH_CHAIN_ID: 4
    volumes:
    - type: bind
      source: ./chain.json
      target: /tmp/chain.json
    ports:
     - "127.0.0.1:8081:8081"

  graphql:
    restart: unless-stopped
    depends_on:
      - db
    image: vulcanize/postgraphile:v1.0.1
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DATABASE=vulcanize_public
      - PG_USER=vdbm
      - PG_PASSWORD=password
      - SCHEMA=public,eth
    ports:
      - "127.0.0.1:5000:5000"

volumes:
  vdb_db_eth_server:
